/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.httprpc.kilo.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import static org.httprpc.kilo.util.Collections.mapOf;

/**
 * Provides a fluent API for programmatically constructing and executing SQL
 * queries.
 */
public class QueryBuilder {
    private StringBuilder sqlBuilder;

    private List<String> parameters = new LinkedList<>();

    private List<Object> generatedKeys = null;

    private static final int INITIAL_CAPACITY = 1024;

    /**
     * Constructs a new query builder.
     */
    public QueryBuilder() {
        this(INITIAL_CAPACITY);
    }

    /**
     * Constructs a new query builder.
     *
     * @param capacity
     * The initial capacity.
     */
    public QueryBuilder(int capacity) {
        sqlBuilder = new StringBuilder(capacity);
    }

    /**
     * @deprecated
     * Use {@link QueryBuilder()} and {@link #append(String)} instead.
     */
    @Deprecated
    public QueryBuilder(String sql) {
        if (sql == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        append(sql);
    }

    private QueryBuilder(StringBuilder sqlBuilder) {
        this.sqlBuilder = sqlBuilder;
    }

    /**
     * Returns the parameters parsed by the query builder.
     *
     * @return
     * The parameters parsed by the query builder.
     */
    public Collection<String> getParameters() {
        return Collections.unmodifiableList(parameters);
    }

    /**
     * Returns the keys that were generated by the query.
     *
     * @return
     * The keys that were generated by the query, or {@code null} if the query
     * did not produce any keys.
     */
    public List<Object> getGeneratedKeys() {
        if (generatedKeys != null) {
            return Collections.unmodifiableList(generatedKeys);
        } else {
            return null;
        }
    }

    /**
     * @deprecated
     * Use {@link #select(SchemaElement...)} instead.
     */
    @Deprecated
    public static QueryBuilder select(String... columns) {
        if (columns == null || columns.length == 0) {
            throw new IllegalArgumentException();
        }

        var sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        sqlBuilder.append("select ");

        var queryBuilder = new QueryBuilder(sqlBuilder);

        for (var i = 0; i < columns.length; i++) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            queryBuilder.append(columns[i]);
        }

        return queryBuilder;
    }

    /**
     * Creates a "select" query.
     *
     * @param schemaElements
     * A list of schema elements representing the columns to select.
     *
     * @return
     * The new {@link QueryBuilder} instance.
     */
    public static QueryBuilder select(SchemaElement... schemaElements) {
        if (schemaElements == null || schemaElements.length == 0) {
            throw new IllegalArgumentException();
        }

        var sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        sqlBuilder.append("select ");

        for (var i = 0; i < schemaElements.length; i++) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            var schemaElement = schemaElements[i];

            sqlBuilder.append(schemaElement.getColumnName());

            var alias = schemaElement.getAlias();

            if (alias != null) {
                sqlBuilder.append(" as ");
                sqlBuilder.append(alias);
            }
        }

        return new QueryBuilder(sqlBuilder);
    }

    /**
     * @deprecated
     * Use {@link #from(Class)} instead.
     */
    @Deprecated
    public QueryBuilder from(String... tables) {
        if (tables == null || tables.length == 0) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" from ");
        sqlBuilder.append(String.join(", ", tables));

        return this;
    }

    /**
     * Appends a "from" clause to a "select" query.
     *
     * @param schemaType
     * The schema type representing the table to select from.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder from(Class<? extends SchemaElement> schemaType) {
        if (schemaType == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" from ");
        sqlBuilder.append(SchemaElement.getTableName(schemaType));

        return this;
    }

    /**
     * @deprecated
     * Use {@link #append(String)} instead.
     */
    @Deprecated
    public QueryBuilder from(QueryBuilder queryBuilder, String alias) {
        if (queryBuilder == null || alias == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" from (");

        append(queryBuilder);

        sqlBuilder.append(") ");
        sqlBuilder.append(alias);

        return this;
    }

    /**
     * @deprecated
     * Use {@link #append(String)} instead.
     */
    @Deprecated
    public QueryBuilder into(String table, String... columns) {
        if (table == null || columns == null) {
            throw new IllegalArgumentException();
        }

        var stringBuilder = new StringBuilder(256);

        stringBuilder.append("insert into ");
        stringBuilder.append(table);

        if (columns.length > 0) {
            stringBuilder.append(" (");

            for (var i = 0; i < columns.length; i++) {
                if (i > 0) {
                    stringBuilder.append(", ");
                }

                stringBuilder.append(columns[i]);
            }

            stringBuilder.append(")");
        }

        stringBuilder.append(" ");

        sqlBuilder.insert(0, stringBuilder);

        return this;
    }

    /**
     * @deprecated
     * Use {@link #join(Class)} instead.
     */
    @Deprecated
    public QueryBuilder join(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" join ");
        sqlBuilder.append(table);

        return this;
    }

    /**
     * Appends a "join" clause to a query.
     *
     * @param schemaType
     * The schema type representing the table to join on.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder join(Class<? extends SchemaElement> schemaType) {
        if (schemaType == null) {
            throw new IllegalArgumentException();
        }

        return join(null, schemaType);
    }

    /**
     * @deprecated
     * Use {@link #append(String)} instead.
     */
    @Deprecated
    public QueryBuilder join(QueryBuilder queryBuilder, String alias) {
        if (queryBuilder == null || alias == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" join (");

        append(queryBuilder);

        sqlBuilder.append(") ");
        sqlBuilder.append(alias);

        return this;
    }

    /**
     * @deprecated
     * Use {@link #leftJoin(Class)} instead.
     */
    @Deprecated
    public QueryBuilder leftJoin(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" left join ");
        sqlBuilder.append(table);

        return this;
    }

    /**
     * Appends a "left join" clause to a query.
     *
     * @param schemaType
     * The schema type representing the table to join on.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder leftJoin(Class<? extends SchemaElement> schemaType) {
        if (schemaType == null) {
            throw new IllegalArgumentException();
        }

        return join("left", schemaType);
    }

    /**
     * @deprecated
     * Use {@link #rightJoin(Class)} instead.
     */
    @Deprecated
    public QueryBuilder rightJoin(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" right join ");
        sqlBuilder.append(table);

        return this;
    }

    /**
     * Appends a "right join" clause to a query.
     *
     * @param schemaType
     * The schema type representing the table to join on.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder rightJoin(Class<? extends SchemaElement> schemaType) {
        if (schemaType == null) {
            throw new IllegalArgumentException();
        }

        return join("right", schemaType);
    }

    private QueryBuilder join(String type, Class<? extends SchemaElement> schemaType) {
        if (type != null) {
            sqlBuilder.append(" ");
            sqlBuilder.append(type);
        }

        sqlBuilder.append(" join ");
        sqlBuilder.append(SchemaElement.getTableName(schemaType));

        return this;
    }

    /**
     * @deprecated
     * Use {@link #on(PredicateComponent...)} instead.
     */
    @Deprecated
    public QueryBuilder on(String... predicates) {
        return filter("on", predicates);
    }

    /**
     * Appends an "on" clause to a query.
     *
     * @param predicateComponents
     * The predicate components.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder on(PredicateComponent... predicateComponents) {
        // TODO
        return this;
    }

    /**
     * Appends a "where" clause to a query.
     *
     * @param predicates
     * The clause predicates.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder where(String... predicates) {
        return filter("where", predicates);
    }

    /**
     * Appends a "where exists" clause to a query.
     *
     * @param queryBuilder
     * The "exists" subquery.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder whereExists(QueryBuilder queryBuilder) {
        if (queryBuilder == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" where exists (");

        append(queryBuilder);

        sqlBuilder.append(")");

        return this;
    }

    /**
     * Appends a "where not exists" clause to a query.
     *
     * @param queryBuilder
     * The "not exists" subquery.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder whereNotExists(QueryBuilder queryBuilder) {
        if (queryBuilder == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" where not exists (");

        append(queryBuilder);

        sqlBuilder.append(")");

        return this;
    }

    /**
     * Appends a "group by" clause to a query.
     *
     * @param columns
     * The column names.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder groupBy(String... columns) {
        if (columns == null || columns.length == 0) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" group by ");
        sqlBuilder.append(String.join(", ", columns));

        return this;
    }

    /**
     * Appends a "having" clause to a query.
     *
     * @param predicates
     * The clause predicates.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder having(String... predicates) {
        return filter("having", predicates);
    }

    private QueryBuilder filter(String clause, String... predicates) {
        if (predicates == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" ");
        sqlBuilder.append(clause);
        sqlBuilder.append(" ");

        for (var i = 0; i < predicates.length; i++) {
            if (i > 0) {
                sqlBuilder.append(" ");
            }

            append(predicates[i]);
        }

        return this;
    }

    /**
     * Appends an "order by" clause to a query.
     *
     * @param columns
     * The column names.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder orderBy(String... columns) {
        if (columns == null || columns.length == 0) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" order by ");
        sqlBuilder.append(String.join(", ", columns));

        return this;
    }

    /**
     * Appends a "limit" clause to a query.
     *
     * @param count
     * The limit count.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder limit(int count) {
        if (count < 0) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" limit ");
        sqlBuilder.append(count);

        return this;
    }

    /**
     * Appends a "for update" clause to a query.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder forUpdate() {
        sqlBuilder.append(" for update");

        return this;
    }

    /**
     * Appends a "union" clause to a query.
     *
     * @param queryBuilder
     * The query builder to append.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder union(QueryBuilder queryBuilder) {
        if (queryBuilder == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" union ");

        append(queryBuilder);

        return this;
    }

    /**
     * Creates an "insert into" query.
     *
     * @param table
     * The table name.
     *
     * @return
     * The new {@link QueryBuilder} instance.
     */
    public static QueryBuilder insertInto(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        var sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        sqlBuilder.append("insert into ");
        sqlBuilder.append(table);

        return new QueryBuilder(sqlBuilder);
    }

    /**
     * Appends column values to an "insert into" query. Keys represent
     * column names. Values are encoded as described below.
     *
     * @param values
     * The values to insert. If a value is an instance of {@link QueryBuilder},
     * it is considered a subquery and is wrapped in parentheses. List values
     * are considered "options" and are reduced to a single value via the SQL
     * {@code coalesce()} function. All other values are encoded as is.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder values(Map<String, ?> values) {
        if (values == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" (");

        List<String> columns = new ArrayList<>(values.keySet());

        var n = columns.size();

        for (var i = 0; i < n; i++) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            sqlBuilder.append(columns.get(i));
        }

        sqlBuilder.append(") values (");

        for (var i = 0; i < n; i++) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            encode(values.get(columns.get(i)));
        }

        sqlBuilder.append(")");

        return this;
    }

    /**
     * @deprecated
     * Use {@link #onDuplicateKeyUpdate(Map)} instead.
     */
    @Deprecated
    public QueryBuilder onDuplicateKeyUpdate(String... columns) {
        if (columns == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" on duplicate key update ");

        for (var i = 0; i < columns.length; i++) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            var column = columns[i];

            sqlBuilder.append(column);
            sqlBuilder.append(" = value(");
            sqlBuilder.append(column);
            sqlBuilder.append(")");
        }

        return this;
    }

    /**
     * Appends an "on duplicate key update" clause to a query.
     *
     * @param values
     * The values to update.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder onDuplicateKeyUpdate(Map<String, ?> values) {
        if (values == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" on duplicate key update ");

        var i = 0;

        for (var entry : values.entrySet()) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            sqlBuilder.append(entry.getKey());
            sqlBuilder.append(" = ");

            encode(entry.getValue());

            i++;
        }

        return this;
    }

    /**
     * Creates an "update" query.
     *
     * @param table
     * The table name.
     *
     * @return
     * The new {@link QueryBuilder} instance.
     */
    public static QueryBuilder update(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        var sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        sqlBuilder.append("update ");
        sqlBuilder.append(table);

        return new QueryBuilder(sqlBuilder);
    }

    /**
     * Appends column values to an "update" query. Keys represent column names.
     * Values are encoded as described for {@link #values(Map)}.
     *
     * @param values
     * The values to update.
     *
     * @return
     * The {@link QueryBuilder} instance.
     */
    public QueryBuilder set(Map<String, ?> values) {
        if (values == null) {
            throw new IllegalArgumentException();
        }

        sqlBuilder.append(" set ");

        var i = 0;

        for (Map.Entry<String, ?> entry : values.entrySet()) {
            if (i > 0) {
                sqlBuilder.append(", ");
            }

            sqlBuilder.append(entry.getKey());
            sqlBuilder.append(" = ");

            encode(entry.getValue());

            i++;
        }

        return this;
    }

    /**
     * Creates a "delete from" query.
     *
     * @param table
     * The table name.
     *
     * @return
     * The new {@link QueryBuilder} instance.
     */
    public static QueryBuilder deleteFrom(String table) {
        if (table == null) {
            throw new IllegalArgumentException();
        }

        var sqlBuilder = new StringBuilder(INITIAL_CAPACITY);

        sqlBuilder.append("delete from ");
        sqlBuilder.append(table);

        return new QueryBuilder(sqlBuilder);
    }

    /**
     * Appends arbitrary SQL text to a query. Named parameters can be declared
     * by prepending a colon to an argument name.
     *
     * @param sql
     * The SQL text to append.
     */
    public void append(String sql) {
        var quoted = false;

        var n = sql.length();
        var i = 0;

        while (i < n) {
            var c = sql.charAt(i++);

            if (c == ':' && !quoted) {
                var parameterBuilder = new StringBuilder(32);

                while (i < n) {
                    c = sql.charAt(i);

                    if (!Character.isJavaIdentifierPart(c)) {
                        break;
                    }

                    parameterBuilder.append(c);

                    i++;
                }

                if (parameterBuilder.length() == 0) {
                    throw new IllegalArgumentException("Missing parameter name.");
                }

                parameters.add(parameterBuilder.toString());

                sqlBuilder.append("?");
            } else if (c == '?' && !quoted) {
                parameters.add(null);

                sqlBuilder.append(c);
            } else {
                if (c == '\'') {
                    quoted = !quoted;
                }

                sqlBuilder.append(c);
            }
        }
    }

    private void append(QueryBuilder queryBuilder) {
        sqlBuilder.append(queryBuilder);

        parameters.addAll(queryBuilder.parameters);
    }

    private void encode(Object value) {
        if (value instanceof String string) {
            append(string);
        } else if (value instanceof List<?> list) {
            sqlBuilder.append("coalesce(");

            var i = 0;

            for (var element : list) {
                if (i > 0) {
                    sqlBuilder.append(", ");
                }

                encode(element);

                i++;
            }

            sqlBuilder.append(")");
        } else if (value instanceof QueryBuilder queryBuilder) {
            sqlBuilder.append("(");

            append(queryBuilder);

            sqlBuilder.append(")");
        } else {
            sqlBuilder.append(value);
        }
    }

    /**
     * Prepares a query for execution.
     *
     * @param connection
     * The connection on which the query will be executed.
     *
     * @return
     * A prepared statement that can be used to execute the query.
     *
     * @throws SQLException
     * If an error occurs while preparing the query.
     */
    public PreparedStatement prepare(Connection connection) throws SQLException {
        if (connection == null) {
            throw new IllegalArgumentException();
        }

        return connection.prepareStatement(getSQL(), Statement.RETURN_GENERATED_KEYS);
    }

    /**
     * Executes a query.
     *
     * @param statement
     * The statement that will be used to execute the query.
     *
     * @return
     * The query results.
     *
     * @throws SQLException
     * If an error occurs while executing the query.
     */
    public ResultSet executeQuery(PreparedStatement statement) throws SQLException {
        return executeQuery(statement, mapOf());
    }

    /**
     * Executes a query.
     *
     * @param statement
     * The statement that will be used to execute the query.
     *
     * @param arguments
     * The query arguments.
     *
     * @return
     * The query results.
     *
     * @throws SQLException
     * If an error occurs while executing the query.
     */
    public ResultSet executeQuery(PreparedStatement statement, Map<String, ?> arguments) throws SQLException {
        if (statement == null || arguments == null) {
            throw new IllegalArgumentException();
        }

        apply(statement, arguments);

        return statement.executeQuery();
    }

    /**
     * Executes a query.
     *
     * @param statement
     * The statement that will be used to execute the query.
     *
     * @return
     * The number of rows that were affected by the query.
     *
     * @throws SQLException
     * If an error occurs while executing the query.
     */
    public int executeUpdate(PreparedStatement statement) throws SQLException {
        return executeUpdate(statement, mapOf());
    }

    /**
     * Executes a query.
     *
     * @param statement
     * The statement that will be used to execute the query.
     *
     * @param arguments
     * The query arguments.
     *
     * @return
     * The number of rows that were affected by the query.
     *
     * @throws SQLException
     * If an error occurs while executing the query.
     */
    public int executeUpdate(PreparedStatement statement, Map<String, ?> arguments) throws SQLException {
        if (statement == null || arguments == null) {
            throw new IllegalArgumentException();
        }

        apply(statement, arguments);

        var updateCount = statement.executeUpdate();

        try (var generatedKeys = statement.getGeneratedKeys()) {
            if (generatedKeys.next()) {
                var generatedKeysMetaData = generatedKeys.getMetaData();

                var n = generatedKeysMetaData.getColumnCount();

                this.generatedKeys = new ArrayList<>(n);

                for (var i = 0; i < n; i++) {
                    this.generatedKeys.add(generatedKeys.getObject(i + 1));
                }
            } else {
                this.generatedKeys = null;
            }
        }

        return updateCount;
    }

    /**
     * Appends a set of arguments to a prepared statement.
     *
     * @param statement
     * The prepared statement.
     *
     * @param arguments
     * The batch arguments.
     *
     * @throws SQLException
     * If an error occurs while adding the batch.
     */
    public void addBatch(PreparedStatement statement, Map<String, ?> arguments) throws SQLException {
        if (statement == null || arguments == null) {
            throw new IllegalArgumentException();
        }

        apply(statement, arguments);

        statement.addBatch();
    }

    private void apply(PreparedStatement statement, Map<String, ?> arguments) throws SQLException {
        var i = 1;

        for (var parameter : parameters) {
            if (parameter == null) {
                continue;
            }

            statement.setObject(i++, arguments.get(parameter));
        }
    }

    /**
     * @deprecated
     * Use {@link #toString()} instead.
     */
    @Deprecated
    public String getSQL() {
        return toString();
    }

    @Override
    public String toString() {
        return sqlBuilder.toString();
    }
}
